// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RW4Entities.Models;

public partial class R_SysService
{
    /// <summary>
    /// Service Unique Identifier
    /// </summary>
    [Key]
    public long SysServiceId { get; set; }

    /// <summary>
    /// Service code unique Identifier
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string SysServiceCd { get; set; }

    /// <summary>
    /// Service Current Running Status
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string CurrentStatusCd { get; set; }

    /// <summary>
    /// Service Requested Running Status to Update
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string RequestedStatusCd { get; set; }

    /// <summary>
    /// When did Service started last time
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? LastStartedDtTm { get; set; }

    /// <summary>
    /// When did Service Stopped last time
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? LastStoppedDtTm { get; set; }

    /// <summary>
    /// Y = Load the Service configuration again.
    /// </summary>
    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string ReLoadFlg { get; set; }

    public int? RestingTimeTm { get; set; }
}