trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  projectFile: 'RW4BNSFTelemetrySVC/RW4BNSFTelemetrySvc.csproj'
  buildConfiguration: 'Release'
  targetFolder: '$(Build.ArtifactStagingDirectory)/assembly'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: Restore@1
      inputs:
        projectFile: $(projectFile)

    - task: Build@1
      inputs:
        solution: $(projectFile)
        configuration: $(buildConfiguration)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'RW4BNSFTelemetrySVC/bin/$(buildConfiguration)/net6.0/RW4BNSFTelemetrySvc.dll'
        artifactName: 'RW4Tele'
