trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  projectFile: 'RW4BNSFTelemetrySVC/RW4BNSFTelemetrySvc.csproj'  
  buildConfiguration: 'Release'
  targetFolder: '$(Build.ArtifactStagingDirectory)/assembly'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
   
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'  
        installationPath: $(Agent.ToolsDirectory)/dotnet


    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: '**/*.csproj'  

    
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: '**/*.csproj'  
        arguments: '--configuration $(buildConfiguration)'

    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'  
        artifactName: 'drop'
