//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCLOBService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GensetStatus", Namespace="http://webservices.gentrak.startrak.com")]
    public partial class GensetStatus : object
    {
        
        private double batteryVoltageField;
        
        private OCLOBService.Event eventField;
        
        private OCLOBService.FuelStatus fuelField;
        
        private string gensetNumberField;
        
        private OCLOBService.GPSLocation gpsField;
        
        private System.Nullable<System.DateTime> messageTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double batteryVoltage
        {
            get
            {
                return this.batteryVoltageField;
            }
            set
            {
                this.batteryVoltageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCLOBService.Event @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCLOBService.FuelStatus fuel
        {
            get
            {
                return this.fuelField;
            }
            set
            {
                this.fuelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gensetNumber
        {
            get
            {
                return this.gensetNumberField;
            }
            set
            {
                this.gensetNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCLOBService.GPSLocation gps
        {
            get
            {
                return this.gpsField;
            }
            set
            {
                this.gpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> messageTime
        {
            get
            {
                return this.messageTimeField;
            }
            set
            {
                this.messageTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://webservices.gentrak.startrak.com")]
    public partial class Event : object
    {
        
        private int eventCodeField;
        
        private string eventDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eventDescription
        {
            get
            {
                return this.eventDescriptionField;
            }
            set
            {
                this.eventDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuelStatus", Namespace="http://webservices.gentrak.startrak.com")]
    public partial class FuelStatus : object
    {
        
        private double fuelChangeField;
        
        private double fuelInTankField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fuelChange
        {
            get
            {
                return this.fuelChangeField;
            }
            set
            {
                this.fuelChangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fuelInTank
        {
            get
            {
                return this.fuelInTankField;
            }
            set
            {
                this.fuelInTankField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GPSLocation", Namespace="http://webservices.gentrak.startrak.com")]
    public partial class GPSLocation : object
    {
        
        private string cityField;
        
        private string facilityCodeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facilityCode
        {
            get
            {
                return this.facilityCodeField;
            }
            set
            {
                this.facilityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StWorkOrder", Namespace="http://webservices.gentrak.startrak.com")]
    public partial class StWorkOrder : object
    {
        
        private OCLOBService.Asset[] assetField;
        
        private System.Nullable<System.DateTime> inspectionTimeField;
        
        private OCLOBService.Trip tripField;
        
        private string workOrderNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCLOBService.Asset[] asset
        {
            get
            {
                return this.assetField;
            }
            set
            {
                this.assetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> inspectionTime
        {
            get
            {
                return this.inspectionTimeField;
            }
            set
            {
                this.inspectionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCLOBService.Trip trip
        {
            get
            {
                return this.tripField;
            }
            set
            {
                this.tripField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workOrderNumber
        {
            get
            {
                return this.workOrderNumberField;
            }
            set
            {
                this.workOrderNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trip", Namespace="http://webservices.gentrak.startrak.com")]
    public partial class Trip : object
    {
        
        private string destinationField;
        
        private string originField;
        
        private OCLOBService.ArrayOfString routePointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCLOBService.ArrayOfString routePoints
        {
            get
            {
                return this.routePointsField;
            }
            set
            {
                this.routePointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asset", Namespace="http://webservices.gentrak.startrak.com")]
    public partial class Asset : object
    {
        
        private string gensetNumberField;
        
        private string reeferContainerNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gensetNumber
        {
            get
            {
                return this.gensetNumberField;
            }
            set
            {
                this.gensetNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reeferContainerNumber
        {
            get
            {
                return this.reeferContainerNumberField;
            }
            set
            {
                this.reeferContainerNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://webservices.gentrak.startrak.com", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.gentrak.startrak.com", ConfigurationName="OCLOBService.GenTrakApplicationGatewayPortPortType")]
    public interface GenTrakApplicationGatewayPortPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> publishGensetStatusAsync(OCLOBService.GensetStatus in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> publishStWorkOrderAsync(OCLOBService.StWorkOrder in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface GenTrakApplicationGatewayPortPortTypeChannel : OCLOBService.GenTrakApplicationGatewayPortPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class GenTrakApplicationGatewayPortPortTypeClient : System.ServiceModel.ClientBase<OCLOBService.GenTrakApplicationGatewayPortPortType>, OCLOBService.GenTrakApplicationGatewayPortPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GenTrakApplicationGatewayPortPortTypeClient() : 
                base(GenTrakApplicationGatewayPortPortTypeClient.GetDefaultBinding(), GenTrakApplicationGatewayPortPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GenTrakApplicationGatewayPortHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenTrakApplicationGatewayPortPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GenTrakApplicationGatewayPortPortTypeClient.GetBindingForEndpoint(endpointConfiguration), GenTrakApplicationGatewayPortPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenTrakApplicationGatewayPortPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GenTrakApplicationGatewayPortPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenTrakApplicationGatewayPortPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GenTrakApplicationGatewayPortPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenTrakApplicationGatewayPortPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> publishGensetStatusAsync(OCLOBService.GensetStatus in0)
        {
            return base.Channel.publishGensetStatusAsync(in0);
        }
        
        public System.Threading.Tasks.Task<int> publishStWorkOrderAsync(OCLOBService.StWorkOrder in0)
        {
            return base.Channel.publishStWorkOrderAsync(in0);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GenTrakApplicationGatewayPortHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GenTrakApplicationGatewayPortHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://webservice.startrak.com/OOCLDataFeed/services/GenTrakApplicationGatewayPor" +
                        "t");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GenTrakApplicationGatewayPortPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.GenTrakApplicationGatewayPortHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GenTrakApplicationGatewayPortPortTypeClient.GetEndpointAddress(EndpointConfiguration.GenTrakApplicationGatewayPortHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            GenTrakApplicationGatewayPortHttpPort,
        }
    }
}
