// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RW4Entities.Models.RWOBDistributorsEntities;

public partial class T_Events
{
    [Key]
    public long EventId { get; set; }

    public long EventMasterId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EventDtTm { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDtTm { get; set; }

    public long CreatedBy { get; set; }

    public Guid? EventGUID { get; set; }

    [ForeignKey("EventMasterId")]
    [InverseProperty("T_Events")]
    public virtual R_EventMaster EventMaster { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<T_PreNoteEvents> T_PreNoteEvents { get; set; } = new List<T_PreNoteEvents>();

    [InverseProperty("Event")]
    public virtual ICollection<T_PreNoteUnitEvents> T_PreNoteUnitEvents { get; set; } = new List<T_PreNoteUnitEvents>();

    [InverseProperty("Event")]
    public virtual ICollection<T_RailincCERLog> T_RailincCERLog { get; set; } = new List<T_RailincCERLog>();

    [InverseProperty("Event")]
    public virtual ICollection<T_UnitEvents> T_UnitEvents { get; set; } = new List<T_UnitEvents>();
}