// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RW4Entities.Models.RWOBDistributorsEntities;

public partial class T_PreNoteUnitEvents
{
    public long PreNoteUnitId { get; set; }

    public long EventId { get; set; }

    [Key]
    public long T_PreNoteUnitEventId { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("T_PreNoteUnitEvents")]
    public virtual T_Events Event { get; set; }

    [ForeignKey("PreNoteUnitId")]
    [InverseProperty("T_PreNoteUnitEvents")]
    public virtual T_PreNoteUnits PreNoteUnit { get; set; }
}