// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RW4Entities.Models.RWOBDistributorsEntities;

public partial class T_RailincCERLog
{
    [Key]
    public long RailincCERLogId { get; set; }

    public long? PreNoteId { get; set; }

    public long? PreNoteUnitId { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string UnitNumber { get; set; }

    public long EventId { get; set; }

    public Guid? CERLogGUID { get; set; }

    [StringLength(600)]
    public string FileName { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string FleetCd { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDtTm { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("T_RailincCERLog")]
    public virtual T_Events Event { get; set; }

    [ForeignKey("PreNoteId")]
    [InverseProperty("T_RailincCERLog")]
    public virtual T_PreNotes PreNote { get; set; }

    [ForeignKey("PreNoteUnitId")]
    [InverseProperty("T_RailincCERLog")]
    public virtual T_PreNoteUnits PreNoteUnit { get; set; }
}